---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  annotations:
    kubernetes.io/ingress.class: alb
spec:
  selector:
    app: {{ template "name" . }}
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: NodePort
