export const USER_LOGIN = 'USER_LOGIN';
export const STORE_USER = 'STORE_USER';

// filter
export const STORE_ACTIVE_FILTER = 'STORE_ACTIVE_FILTER';
export const STORE_LOADING = 'STORE_LOADING';
export const CLEAR_LOADING = 'CLEAR_LOADING';
export const STORE_CALENDAR_RANGE = 'STORE_CALENDAR_RANGE';

// timeline
export const STORE_TIMELINE_HX = 'STORE_TIMELINE_HX';
export const STORE_TIMELINE_HEATMAP = 'STORE_TIMELINE_HEATMAP';
export const STORE_TIMELINE_ATTENDANCE = 'STORE_TIMELINE_ATTENDANCE';
export const STORE_TIMELINE_DWELL_HEEATMAP = 'STORE_TIMELINE_DWELL_HEEATMAP';
export const CLEAR_TIMELINE = 'CLEAR_TIMELINE';

// centers
export const STORE_CENTERS_WAITING_TIME = 'STORE_CENTERS_WAITING_TIME';
export const STORE_CENTERS_INFO = 'STORE_CENTERS_INFO';
export const STORE_CENTERS_JOURNEY = 'STORE_CENTERS_JOURNEY';
export const STORE_CENTERS_COMMON_JOURNEYS = 'STORE_CENTERS_COMMON_JOURNEYS';
export const STORE_CENTERS_HAPPINESS_AREA = 'STORE_CENTERS_HAPPINESS_AREA';
export const STORE_CENTERS_ZONES = 'STORE_CENTERS_ZONES';
export const STORE_CENTERS_CUSTOMERS = 'STORE_CENTERS_CUSTOMERS';
export const STORE_CENTERS_AREA_STATISTICS = 'STORE_CENTERS_AREA_STATISTICS';
export const STORE_CENTERS_DWELL_STATISTICS = 'STORE_CENTERS_DWELL_STATISTICS';
export const CLEAR_CENTERS = 'CLEAR_CENTERS';
export const STORE_PEOPLE_WAITING_DEMOGRAPHICS =
  'STORE_PEOPLE_WAITING_DEMOGRAPHICS';
